[package]
name = "l2"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
integrity = "2.0.0"
starknet = "2.9.2"
openzeppelin_access = "0.20.0"
openzeppelin_introspection = "0.20.0"
openzeppelin_token = "0.20.0"
openzeppelin_upgrades = "0.20.0"

[dev-dependencies]
assert_macros = "2.9.2"
openzeppelin_utils = "0.20.0"
snforge_std = "0.36.0"

[[target.starknet-contract]]
sierra = true

[scripts]
test = "snforge test"

[[tool.snforge.fork]]
name = "SEPOLIA_LATEST"
url = "https://starknet-sepolia.public.blastapi.io/rpc/v0_7"
block_id.tag = "latest"
